Repository asterisk-java/asterisk-java, pull requests merged in 2022-11, with the labels that each got.

#422 Add issue management info to pom.xml
  pom.xml
Labels: kind/refactor

#423 Introduce new release process based on GitHub Releases and Actions
  .dart_tool/.gitignore
  .github/workflows/nexus.yml
  .github/workflows/release.yml
  pom.xml
  pubspec.lock
  pubspec.yaml
  triggerRelease.dart
Labels: kind/enhancement

#425 Add tests for AgiExecStartEvent
  src/main/java/org/asteriskjava/manager/internal/EventBuilderImpl.java
  src/main/java/org/asteriskjava/manager/internal/ResponseBuilderImpl.java
  src/main/java/org/asteriskjava/manager/util/EventAttributesHelper.java
  src/test/java/org/asteriskjava/manager/event/AgiExecStartEventTest.java
Labels: kind/refactor, module/ami

#426 Add missing properties to ChanSpyStopEvent
  src/main/java/org/asteriskjava/manager/event/ChanSpyStopEvent.java
  src/test/java/org/asteriskjava/manager/event/ChanSpyStopEventTest.java
Labels: kind/enhancement, module/ami

#428 Add `ChannelTalkingStartEvent` and `ChannelTalkingStopEvent` events
  src/main/java/org/asteriskjava/manager/event/AbstractChannelTalkingEvent.java
  src/main/java/org/asteriskjava/manager/event/ChannelTalkingStartEvent.java
  src/main/java/org/asteriskjava/manager/event/ChannelTalkingStopEvent.java
  src/test/java/org/asteriskjava/manager/event/ChannelTalkingStartEventTest.java
  src/test/java/org/asteriskjava/manager/event/ChannelTalkingStopEventTest.java
Labels: kind/enhancement, module/ami

#429 Add tests for `AgentConnectEvent`
  src/test/java/org/asteriskjava/manager/event/AgentConnectEventTest.java
Labels: kind/refactor, module/ami

#430 Add missing tests
  src/test/java/org/asteriskjava/manager/event/BridgeCreateEventTest.java
  src/test/java/org/asteriskjava/manager/event/BridgeEnterEventTest.java
  src/test/java/org/asteriskjava/manager/event/ConfbridgeJoinEventTest.java
  src/test/java/org/asteriskjava/manager/event/ConfbridgeLeaveEventTest.java
  src/test/java/org/asteriskjava/manager/event/HangupEventTest.java
  src/test/java/org/asteriskjava/manager/event/HangupRequestEventTest.java
  src/test/java/org/asteriskjava/manager/event/MusicOnHoldEventTest.java
Labels: kind/refactor, module/ami

#431 Add `recordFile` field to `ConfbridgeStartRecordAction`
  src/main/java/org/asteriskjava/manager/action/ConfbridgeStartRecordAction.java
Labels: kind/enhancement, module/ami

#432 Add missing fields to `SipShowPeerResponse`
  src/main/java/org/asteriskjava/manager/response/SipShowPeerResponse.java
  src/test/java/org/asteriskjava/manager/response/SipShowPeerResponseTest.java
Labels: kind/enhancement, module/ami

#434 Add missing tests for `AttendedTransferEvent`
  src/test/java/org/asteriskjava/manager/event/AttendedTransferEventTest.java
Labels: kind/refactor, module/ami

#435 Add supported AMI version for Asterisk 20
  src/main/java/org/asteriskjava/manager/internal/ManagerConnectionImpl.java
Labels: kind/enhancement, module/ami, asterisk/20

#439 Support for AMI versions 8.0 for Asterisk 19 and 9.0 for Asterisk 20
  src/main/java/org/asteriskjava/manager/internal/ManagerConnectionImpl.java
Labels: kind/bug, module/ami, asterisk/20

#441 Add asterisk 19 and 20 as a supported versions
  src/main/java/org/asteriskjava/AsteriskVersion.java
Labels: kind/enhancement, asterisk/20

#447 Add asterisk 18 certified a supported version (#446)
  src/main/java/org/asteriskjava/AsteriskVersion.java
  src/test/java/org/asteriskjava/AsteriskVersionTest.java
Labels: kind/enhancement, asterisk/18
